# .azure-pipelines/templates/stage-apply.yml
parameters:
  - name: workingDirectory
    type: string
  - name: serviceConnection
    type: string
  #- name: copyWorkloadFiles
  #  type: boolean
  #  default: false

stages:
  - stage: Apply
    displayName: 'Terraform Apply'
    dependsOn: Approval
    jobs:
      - deployment: TerraformApply
        displayName: 'Apply'
        environment: terraform
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  persistCredentials: true

                #- ${{ if eq(parameters.copyWorkloadFiles, true) }}:
                #  - task: DownloadPipelineArtifact@2
                #    displayName: 'Downloading workload files (init.tf and terraform.tfvars)'
                #    inputs:
                #      buildType: current
                #      artifact: workload-$(Build.BuildId)
                #      path: ${{ parameters.workingDirectory }}
                  
                - bash: |
                    export BINDIR=~/bin
                    mkdir -p $BINDIR
                    curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | bash
                  displayName: 'Installing tfswitch'

                - bash: $HOME/bin/tfswitch -b $HOME/bin/terraform
                  displayName: 'Setting Terraform Version'
                  workingDirectory: ${{ parameters.workingDirectory }}

                - task: DownloadPipelineArtifact@2
                  displayName: 'Downloading plan file'
                  inputs:
                    buildType: current
                    artifact: tfPlan-$(Build.BuildId)
                    path: ${{ parameters.workingDirectory }}

                - task: AzureCLI@2
                  displayName: 'Applying terraform plan'
                  env:
                    AZDO_PERSONAL_ACCESS_TOKEN: $(System.AccessToken)
                  inputs:
                    azureSubscription: ${{ parameters.serviceConnection }}
                    scriptType: bash
                    scriptLocation: inlineScript
                    addSpnToEnvironment: true
                    workingDirectory: ${{ parameters.workingDirectory }}
                    inlineScript: |
                      $HOME/bin/terraform init
                      $HOME/bin/terraform apply --auto-approve planfile
